/** Global Options */
export const NOTIFIER_GLOBAL_MODULE_OPTIONS = 'NOTIFIER_GLOBAL_MODULE_OPTIONS'

/** Services */
export const NOTIFIER = 'NOTIFIER'
export const NOTIFIER_EMAIL_SERVICE = 'NOTIFIER_EMAIL_SERVICE'
export const NOTIFIER_FIREBASE_SERVICE = 'notifier_FIREBASE_SERVICE'
